baseURL = "https://zhangk.github.io/my-joplin-notes/"
languageCode = "en-us"
title = "My Joplin Notes"
# 完全不设置 theme

# 禁用一些需要主题的功能
disableKinds = ["RSS", "taxonomy", "term"]

# 只生成页面
[outputs]
  home = ["HTML"]
  page = ["HTML"]
