baseURL = "https://zhangk.github.io/my-joplin-notes/"
languageCode = "en-us"
title = "My Joplin Notes"
theme = "PaperMod"

# PaperMod 基本配置
[params]
  homeInfoMode = "PostList"
  socialIcons = false

# 启用摘要
summaryLength = 100

# 菜单（可选）
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
